pipeline:
  name: xzcxzv
  identifier: xzcxzv
  projectIdentifier: RajathaTest2
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubrajatha
        build:
          spec:
            branch: main
          type: branch
  stages:
    - stage:
        name: xcvvcx
        identifier: xcvvcx
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: xzvzx
                  identifier: xzvzx
                  spec:
                    shell: Sh
                    command: |-
                      echo hello
                      #---data
                      echo 1 
                  timeout: 1m
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  allowStageExecutions: true
  delegateSelectors:
    - ciaccountdelegate
  timeout: 1d
  notificationRules:
    - name: abc
      identifier: abc
      pipelineEvents:
        - type: StageFailed
          forStages:
            - xcvvcx
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - rajatha.ranganath@harness.io
      enabled: true
